server:
  port: 9090

#日志配置
logging:
  config: classpath:log/log4j2-spring.xml

spring:
  kafka:
    bootstrap-servers: 159.75.2.217:9092
    consumer:
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      auto-offset-reset: earliest
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3  #  重试次数
  redis:
    database: 0
    host: 159.75.2.217
    port: 6379
    timeout: 10000
kafka:
  topic:
    my-topic: my-topic